### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by pavel-b-novikov** [em881g/nsudotnet#2]
![image](https://cloud.githubusercontent.com/assets/2521412/7787504/c6266228-0231-11e5-9b09-e422d884bc28.png)

Чтобы этого exception-а не было, надо отключить Lazy loading.
Вопрос - почему так и при чем здесь Projections?

**Comment by pavel-b-novikov** [comment]
Exception detail прилагаю

![image](https://cloud.githubusercontent.com/assets/2521412/7787507/0dc3325a-0232-11e5-95e1-7b4e1192c531.png)

**Comment by em881g** [comment]
Проблема в том, что имеем одно соединение, и предыдущий DataReader не закончил исполнение, а в это время мы пытаемся считать новую порцию данных

**Comment by pavel-b-novikov** [comment]
Слишком размыто и абстрактно. 
А чего это вдруг нельзя открыть новый DataReader? Что ему мешает? 
И где это мы читаем новую порцию данных? 
Больше конкретики, больше.

**Comment by em881g** [comment]
Нельзя открыть, потому что работаем через одно единственное подключение к базе данных.
SiteEntity.(тянем из БД)SiteManager.(снова тянем из БД)Engineer

**Comment by pavel-b-novikov** [comment]
А как одно подключение ограничевает создание DataReader? Уж не потому ли что злобный Microsoft явно запретил это делать в конструкторе DataReader? (sarcasm)

**Comment by em881g** [comment]
Очевидно, что кидать данные через одну трубку это достаточно рискованный шаг. Кто их получит тоже резонный вопрос?

**Comment by pavel-b-novikov** [comment]
Штоэ? О_о

**Comment by em881g** [comment]
Допустим два DataReader'a сделали запрос к БД,потом БД начинает слать результат обратно. Кто что получит остается загадкой.

**Comment by pavel-b-novikov** [comment]
Антон, вы не ответите на этот вопрос правильно, пока не узнаете что конкретно делает DataReader для того, чтобы достать данные.

**Comment by em881g** [comment]
Только один DataReader может использовать открытое соединение. 
Что делает DataReader - вычитывает данные из таблицы в буфер, а когда приложению необходимо получить строку из таблицы - возвращает ее из буфера. 
Преимущества такого подхода в том, что если имеем записи в таблице в несколько байт, то делать запрос на получение строки, каждый раз, когда просят, - глупо и расточительно.

**Comment by pavel-b-novikov** [comment]
Из какой таблицы? В какой буфер? О_о 
Антон, проснитесь, вы увязли в матрице.
Т.е. вы реально думаете что таблицу в несколько гигабайт DataReader считает в память? Т.е. вот у нас есть запрос, например, на выборку всех сайтов (в вашей системе). И на него тоже открывается DataReader (!) и повлиять на это поведение вы не можете. Если руководствоваться вашими словами, DR должен вычитать в RAM весь результат селекта, так чтоли?
Ну так это ни разу не соответствует реальности.

**Comment by em881g** [comment]
Да действительно, по моим словам так и выходит, наверное. DataReader делает запрос к БД, результат запроса хранится в "network buffer" ((c) MSDN, и да, я понимаю, что подразумевается, просто не могу нормально перевести). А когда вызывается метод Read, то DR вычитывает эти данные из этого буфера. А что бы их не потерять, ни какой другой объект не должен работать с соединением.

**Comment by pavel-b-novikov** [comment]
Представим что вы вычитываете 8 гигабайт данных из БД.
Вашими словами, networkbuffer должен располагаться на отдельном сервере для такого дела...
В реальности этого почему-то не происходит.

**Comment by em881g** [comment]
Подождите. Я не говорю что ВСЕ 8 гб будут сохраняться в этот буфер, это же идиотизм. Скорее всего DR после того, как начал вычитывать первую порцию данных, просит следующую.

**Comment by em881g** [comment]
Как я понял, основная идея DR в том, что бы хранить в RAM строго указанное число записей. Поэтому он пользуется network buffer'ом для буферизации.

**Comment by pavel-b-novikov** [comment]
И где вы строго указали число записей? :)

**Comment by em881g** [comment]
По дефолту 1

**Comment by pavel-b-novikov** [comment]
Бугога.
Т.е. я правильно понимаю, что DataReader делает SELECT TOP 1 ..., потом, когда вы считали данные, он делает SELECT TOP ... OFFSET 1 LIMIT 1 и т.п.?

**Comment by em881g** [comment]
Нет. Запрашивает он большее число, потому что - "Преимущества такого подхода в том, что если имеем записи в таблице в несколько байт, то делать запрос на получение строки, каждый раз, когда просят, - глупо и расточительно."
Но в RAM хранит число строк не больше указанного числа (1 по дефолту) .

**Comment by pavel-b-novikov** [comment]
Стоп. А остальные где хранятся тогда?

**Comment by em881g** [comment]
Остальные строки из отдельно взятой "пачки полученных данных" хранятся в networkbuffer'e.
Размер пачки обычно, по слухам, 8кб

**Comment by pavel-b-novikov** [comment]
Так а networkbuffer что - не в RAM лежит чтоли?

**Comment by em881g** [comment]
Точно не скажу, знаю только то, что им управляет система, и он определенного размера.

**Comment by pavel-b-novikov** [comment]
(facepalm) x 3

https://msdn.microsoft.com/en-us/library/ms181441(v=sql.105).aspx

Осознайте какую чушь вы написали и покайтесь.

**Comment by em881g** [comment]
Я правильно понимаю, что вы хотели услышать от меня что-то о курсорах?

**Comment by em881g** [comment]
Просто о DR я брал инфу здесь - https://msdn.microsoft.com/en-us/library/ms254509(v=vs.80).aspx

**Comment by em881g** [comment]
И да, я каюсь, что вообще не упомянул про курсоры.

**Comment by pavel-b-novikov** [comment]
> Я правильно понимаю, что вы хотели услышать от меня что-то о курсорах?

Антон, естественно! DR открывает курсор на выбранном запросе и подключении, а вовсе не читает данные полностью в какой-то буфер. Ну и упирается все в то, что вложенный курсор в контексте юзкейза датаридера открыть не представляется возможным.

**Comment by em881g** [comment]
Так действительно яснее
